### ISSUE TITLE
As dev/ops I want more control over the proxy config

### ISSUE THREAD

**Issue by jvanveen** [molgenis/molgenis-ops-helm#298]
### Which chart are you referring?
molgenis-frontend

### How to reproduce
I would like the option to customize the content of a config file. For instance, in lifelines-webshop/values.yaml, I want to add custom.conf like:

```
custom: |-
  location /edge-server/ {
    proxy_pass http://lifelines-edge/edge-server/;}
  location /vuepdf {
     proxy_pass http://vue-pdfium/vuepdf;}
  location /vuepdf-dev {
     proxy_pass http://vue-pdfium/vuepdf-dev/;}
```
Notice the missing trailing slash in location /vuepdf.
Currently, the config can only be defined like:
```
custom:
    - path: "edge-server"
      url: "http://lifelines-edge/edge-server"
      unpkg: false
    - path: "vuepdf"
      url: "http://vue-pdfium/vuepdf"
      unpkg: false
    - path: "vuepdf-dev"
      url: "http://vue-pdfium/vuepdf-dev"
      unpkg: false
```

Which produces proxy config like:
```
location /vuepdf/ {
   proxy_pass http://vue-pdfium/vuepdf/;}
```
With the trailing slashes, Nginx makes a 301 redirect from a POST to the proxy, which results in a failing endpoint.
